(*

Exercise 00
Exercise 00: The Set module and the Set.Make functor
Turn-in directory : ex00/
Files to turn in : ex00.ml
Allowed functions : The Set module
OCaml’s STD lib provides a Set module. This module hides an implementation of sets
based on trees. As a consequence, such an efficient implementation of sets needs ordered
elements to build the inner tree. The implementation of a set is completly dependant of
the type of its elements, that’s why OCaml’s sets are generated by a functor. The Set
module exposes 3 things:
OrderedType : The signature of the parameter of the functor.
S : The signature of the actual generated set.
Make : The actual functor to create a set from an ordered type.
Copy the following lines into the file "ex00.ml":
let () =
let set = List.fold_right StringSet.add [ "foo"; "bar"; "baz"; "qux" ] StringSet.empty in
StringSet.iter print_endline set;
print_endline (StringSet.fold ( ^ ) set "")
Complete the file "ex00.ml" in order to achieve the following output:
$> ocamlopt ex00.ml && ./a.out
bar
baz
foo
qux
quxfoobazbar
$

 *)




module StringSet = Set.Make(
  struct
    type t = String.t
    let compare = String.compare
  end
)

let () =
  let set =
    List.fold_right StringSet.add [ "foo"; "bar"; "baz"; "qux" ] StringSet.empty
  in
  StringSet.iter print_endline set;
  print_endline (StringSet.fold ( ^ ) set "")
